--- #YAML:1.0
name:               Toss
version:            0.0.1
abstract:           Error or Warning management without eval
author:
    - Todd Rinaldo <toddr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
    Test::NoWarnings:     0
requires:
    DateTime:           0
    Devel::StackTrace:  0
    overload:           0
    Test::More:         0
    Test::NoWarnings:   0
    version:            0
resources:
    bugtracker:  http://github.com/toddr/perl-Toss/issues
    homepage:    http://wiki.github.com/toddr/perl-Toss
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/toddr/perl-Toss/tree/master
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
